### ISSUE TITLE
Opensearch: Cannot add trace to logs

### ISSUE THREAD

**Issue by framctr** [grafana/opensearch-datasource#339] opened 2024-02-28 10:53 UTC
**What happened**:
It is not possible to add opensearch datasource in jaeger datasource in the trace to logs field.

**What you expected to happen**:
Opensearch datasource added in the trace to logs datasource

**How to reproduce it (as minimally and precisely as possible)**:
Create k8s cluster with jaeger and opensearch, configure datasources and try to add opensearch to "trace to logs".

Linked to #79 

**Environment**:
- Grafana version: 9.1.6
- OpenSearch version: 2.4.0
- Plugin version: opensearch 2.14.4

**Comment by idastambuk** [comment] 2024-02-29 15:00
hi @framctr can you tell us more specifically about what kind of problem you're encountering? 

The way I'm reproducing it: 

1. added an opensearch datasource
2. added a jaeger datasource
3. Under "Traces to logs" section in Jaeger configuration, I am able to select Open Search datasource and enter a custom query 
4. the query is populated in the OpenSearch datasource from Jaeger results

**Comment by idastambuk** [comment] 2024-03-25 09:05
Hi @framctr since we haven't had a response and we're unable to reproduce this, I will close the issue. Hope the above steps help with getting it working!

**Closed by idastambuk** 2024-03-25 09:05 UTC
Labels: type/bug, datasource/OpenSearch
