### ISSUE TITLE
Migration to a Backend Data Source

### ISSUE THREAD

**Issue by fridgepoet** [grafana/opensearch-datasource#192] opened 2023-06-08 14:48 UTC
```[tasklist]
### Before Node Graph
- [ ] https://github.com/grafana/oss-plugin-partnerships/issues/192
- [ ] https://github.com/grafana/oss-plugin-partnerships/issues/195
- [x] move non-reg dashboard to cloudatasource Cloud instance
- [ ] https://github.com/grafana/opensearch-datasource/issues/185
- [ ] https://github.com/grafana/opensearch-datasource/issues/175
- [ ] https://github.com/grafana/opensearch-datasource/issues/196
- [x] Prerequisite for Lucene work below: https://github.com/grafana/opensearch-datasource/issues/224
- [ ] https://github.com/grafana/opensearch-datasource/issues/195
- [ ] https://github.com/grafana/opensearch-datasource/issues/199
- [ ] https://github.com/grafana/opensearch-datasource/issues/248
- [ ] https://github.com/grafana/opensearch-datasource/issues/226
- [ ] https://github.com/grafana/oss-plugin-partnerships/issues/199
- [ ] https://github.com/grafana/opensearch-datasource/issues/255
- [ ] https://github.com/grafana/opensearch-datasource/issues/197
- [ ] https://github.com/grafana/opensearch-datasource/issues/200
- [ ] https://github.com/grafana/opensearch-datasource/issues/201
- [ ] https://github.com/grafana/opensearch-datasource/issues/156
- [ ] https://github.com/grafana/opensearch-datasource/issues/223
```

```[tasklist]
### After Node Graph
- [ ] https://github.com/grafana/opensearch-datasource/issues/296
- [ ] https://github.com/grafana/opensearch-datasource/issues/275
- [ ] https://github.com/grafana/opensearch-datasource/issues/290
- [ ] https://github.com/grafana/opensearch-datasource/issues/372
- [ ] https://github.com/grafana/opensearch-datasource/issues/373
- [ ] https://github.com/grafana/opensearch-datasource/issues/374
- [ ] https://github.com/grafana/opensearch-datasource/issues/379
- [x] https://github.com/grafana/opensearch-datasource/issues/161 (Investigate which queries this change may need to be applied to https://github.com/grafana/grafana/pull/67767)
- [ ] https://github.com/grafana/opensearch-datasource/issues/407
```

```[tasklist]
### Related bugs
- [ ] https://github.com/grafana/opensearch-datasource/issues/176
- [ ] https://github.com/grafana/opensearch-datasource/issues/173
- [ ] https://github.com/grafana/opensearch-datasource/issues/181
```

**Comment by katebrenner** [comment] 2024-05-10 13:08
**Project Update**

**Highlight**
All the queries are running in the backend in both explore and dashboards (explore-only restriction has been removed), besides PPL time series format, which is just in explore.

**Trending**


🟢 on track


**Next**

- release https://github.com/grafana/opensearch-datasource/pull/377/
- [remove explore-only restriction for PPL time series format](https://github.com/grafana/opensearch-datasource/issues/379)

**Comment by katebrenner** [comment] 2024-05-20 14:32
**Project Update**

**Highlight**
Reverting due to 2 bugs - https://github.com/grafana/opensearch-datasource/issues/389 and https://github.com/grafana/opensearch-datasource/issues/388

**Trending**


🟢 on track


**Next**

Fix the 2 bugs related to the migration, so we can revert the revert

**Comment by kevinwcyu** [comment] 2024-05-31 19:34
**Project Update**

**Highlight**
#379 and #389 are in review

**Trending**


🟢 on track


**Next**


One more bug fix #388 needs to be completed and then we can route all queries to the backend

**Comment by kevinwcyu** [comment] 2024-06-07 21:18
**Project Update**

**Highlight**
#379 and #389 are completed
#388 closed due to lack of reproduction instructions
#405 pr opened

**Trending**


🟢 on track


**Next**


#407 will add feature flag to start executing queries from dashboards through the backend path

**Comment by kevinwcyu** [comment] 2024-06-14 17:04
**Project Update**

**Highlight**
PRs opened and ready to merge for adding feature toggle to roll out dashboard queries through the backend.
[PR to add feature toggle in Grafana](https://github.com/grafana/grafana/pull/89208)
[PR to use feature toggle in OpenSearch data source](https://github.com/grafana/opensearch-datasource/pull/409)

**Trending**


🟢 on track


**Next**


Will start rolling out the feature toggle up to canary once the above PRs are merged.

**Comment by kevinwcyu** [comment] 2024-06-24 15:05
**Project Update**

**Highlight**
Rolled out feature toggle to send dashboard queries to the backend in dev, staging, and canary.

**Trending**


🟢 on track


**Next**


Will starting rolling it out to prod for 30% of users and let it bake for a bit.

**Comment by kevinwcyu** [comment] 2024-06-27 15:04
**Project Update**

**Highlight**
Rolled out feature toggle to prod for 30% of users.

**Trending**


🟢 on track


**Next**


Roll out to 60% of users in prod and let it bake for a bit before rolling it out to 100% of users.

**Comment by kevinwcyu** [comment] 2024-07-05 15:42
**Project Update**

**Highlight**
Rolled out feature toggle to prod for 65% of users.

**Trending**


🟢 on track


**Next**


Roll out to 100% of users in prod.

**Comment by kevinwcyu** [comment] 2024-07-17 17:21
**Project Update**

**Highlight**
Rolled out feature toggle to prod for 100% of users.

**Trending**


🟢 on track


**Next**

This epic is done

**Closed by kevinwcyu** 2024-07-17 17:21 UTC
Labels: datasource/OpenSearch, type/epic
