### ISSUE TITLE
Group By Terms does not work in alert rules

### ISSUE THREAD

**Issue by ReneZeidler** [grafana/opensearch-datasource#57] opened 2022-08-02 12:31 UTC
Within alert rules, queries using "Group By Terms" do not return any results, while the same query using an Elasticsearch datasource works correctly:
![groupby](https://user-images.githubusercontent.com/5558742/182374420-5bbe267b-b370-4124-8cdb-e68ee76c1132.png)

Using the same query in a panel does work correctly:
![panel](https://user-images.githubusercontent.com/5558742/182374799-ceaeb659-b8db-4634-b281-e1f178ea4e00.png)

- Grafana version: v9.0.5 (1b595e434a)
- Data source type & version: OpenSearch 2.0.0
- OS Grafana is installed on: Using Docker image `grafana/grafana:9.0.5` on an Ubuntu 20.04.3 LTS host

**Comment by svennergr** [comment] 2022-08-08 09:39
Hi @ReneZeidler,

thanks for your report. This is most likely a duplicate of https://github.com/grafana/opensearch-datasource/issues/31. Unfortunately alerting is currently not working in OpenSearch and will be fixed in the near future.

**Closed by svennergr** 2022-08-08 09:39 UTC
Labels: datasource/OpenSearch, needs investigation
