### ISSUE TITLE
Logs Sample

### ISSUE THREAD

**Issue by sarahzinger** [grafana/opensearch-datasource#136] opened 2023-04-13 14:23 UTC
**What happened**:
This Logs Sample Section keeps appearing for me on the bottom of the explore page even when I'm not making a log query and then I'll click on it and it disappears. I'm not sure what it is. 
![Screenshot 2023-04-13 at 9 31 11 AM](https://user-images.githubusercontent.com/6620164/231789281-21e1991a-1052-45c4-b029-c2b733909108.png)

**Environment**:
- Grafana version: ~9.4
- Plugin version: ~2.2

**Comment by idastambuk** [comment] 2024-01-26 16:03
We can't reproduce anymore, closing this

**Closed by idastambuk** 2024-01-26 16:03 UTC
Labels: type/bug, good first issue, datasource/OpenSearch
