### ISSUE TITLE
Grafana - Cannot read properties of undefined (reading 'digest')

### ISSUE THREAD

**Issue by skycannavod** [grafana/opensearch-datasource#282] opened 2023-10-12 13:59 UTC
![ezgif-4-b007e6297a](https://github.com/grafana/opensearch-datasource/assets/65011422/b8b2b5c6-755b-469c-ba3e-087723bdfb22)

**What happened**: hi, we are trying to view the metrics of the opensearch version on grafana using the opensearch datasource, but the following error is returned once the dashboard is created: Cannot read properties of undefined (reading 'digest')

**What you expected to happen**: we expect the data to appear

**How to reproduce it (as minimally and precisely as possible)**: have grafana version 10.1.2, opensearch version 2.9 (Service software version: OpenSearch_2_9_R20230926), OpenSearch plugin version 2.13.0 and try to make a dashboard with opensearch datasource

**Anything else we need to know?**: 

**Environment**:
- Grafana version: 10.1.2
- OpenSearch version:  2.9
- Plugin version: 2.13.0

**Comment by iwysiu** [comment] 2023-10-17 15:30
Hi @skycannavod ! I haven’t been able to reproduce the issue yet, but I have a few questions:
- What response are you getting from Opensearch for the query? (Please redact any sensitive information, but is it returning an error, what’s the structure of the response, and what headers is it getting?)
- What auth options are you using for your OpenSearch datasource?

**Comment by skycannavod** [comment] 2023-10-18 08:13
grafana gives me the error: "Cannot read properties of undefined (reading 'digest')", if I try to execute the query on "Query Inspector" it remains in a loop

as regards the auth we use the SigV4 auth AWS SDK Default, once the auth and the index pattern have been set, it takes everything correctly, but when I try to view the data on the dashboard it gives me the error explained above

**Comment by iwysiu** [comment] 2023-10-20 18:32
Hi @skycannavod ! I took another look at this, and the [crypto](https://developer.mozilla.org/en-US/docs/Web/API/Crypto) interface that we're using to generate the SigV4 signatures requires that it's run in a secure context. Are you running Grafana in a [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts)?

**Comment by fridgepoet** [comment] 2023-10-26 16:17
Hi @skycannavod I have set up the following locally according to your notes:
* grafana version 10.1.2
* opensearch version 2.9 (Service software version: OpenSearch_2_9_R20230926)
* OpenSearch plugin version 2.13.0
* SigV4 auth AWS SDK Default
* our grafana is on http, opensearch in https (I am building and running grafana on localhost, opensearch hosted on AWS)

Finally, the fact that you have this "wrong" ElasticSearch 7.10.2 version sounds like this [issue](https://github.com/grafana/opensearch-datasource/issues/206) so maybe you [have compatibility mode on](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/createupdatedomains.html#:~:text=Enable%20compatibility%20mode). I also created a datasource with compatibility enabled which gives me a similar version in the OpenSearch plugin. I went to the Dashboard as in your gif and was unable to reproduce your issue.

Here's what I have set up, can you let me know if it's the same as your setup? Also let me know if any of the above differs from your setup.

![Screenshot 2023-10-26 at 18 14 31](https://github.com/grafana/opensearch-datasource/assets/4163034/4279e0a7-0b78-46d3-addd-59f16ad4a657)

**Comment by skycannavod** [comment] 2023-10-27 09:36
Hi, yes the configuration is the same, with compatibility mode on

**Comment by fridgepoet** [comment] 2023-10-27 12:42
Thanks for the info.

I spoke to @sarahzinger about this, and looping back to `our grafana is on http, opensearch in https`, this may be an issue as @iwysiu mentioned above. In my case using `localhost` is [considered secure](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts), but if you are elsewhere this may not be sufficient. You might need to either run Grafana locally or run it somewhere with `https`.

It may be that our [refactor which is still in progress](https://github.com/grafana/opensearch-datasource/issues/192) will resolve this issue for you because it will no longer depend on your browser's context security. This work is done for some queries and not for others. As a test, would you be able to run a "Raw Data" query and tell us if you still observe the error?
![Screenshot 2023-10-27 at 14 41 47](https://github.com/grafana/opensearch-datasource/assets/4163034/383b1834-ca97-40b4-a414-da0f46cd39f3)

**Comment by fridgepoet** [comment] 2023-10-30 08:18
Once [this refactor](https://github.com/grafana/opensearch-datasource/issues/192) is done, you should be able to see data with your current setup.

Right now you need to either run Grafana locally or run it somewhere with `https`.

**Comment by idastambuk** [comment] 2024-01-30 10:57
Hi @skycannavod can you confirm that this is fixed in the latest version of the plugin? Thanks!

**Comment by skycannavod** [comment] 2024-02-06 15:34
Hi @idastambuk, i confirm that it works
Thanks!

**Closed** 2024-02-06 15:42 UTC
Labels: type/bug, datasource/OpenSearch
